services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./backend/public:/var/www/html
        depends_on:
            - backend
            - mysql
            - frontend
        networks:
            - app

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile

        environment:
            DB_HOST: mysql
            DB_DATABASE: twitter
            DB_USERNAME: root
            DB_PASSWORD: root
            MAIL_MAILER: smtp
            MAIL_HOST: docker.from.mac.localhost
            MAIL_PORT: 1025
        ports:
            - 8000:8000
            - 1025:1025

        volumes:
            - ./backend:/app/backend
            - vendor:/app/backend/vendor

        depends_on:
            - mysql

        networks:
            - app

    frontend:
        build:
            context: .
            dockerfile: frontend/Dockerfile
        tty: true
        ports:
            - 3000:3000
        volumes:
            - ./frontend:/app/frontend
            - ./backend/.env:/app/frontend/.env
            - node_modules:/app/frontend/node_modules
        depends_on:
            - backend
        networks:
            - app

    mysql:
        image: mysql
        environment:
            MYSQL_DATABASE: "twitter"
            MYSQL_USER: "admin"
            MYSQL_PASSWORD: "root"
            MYSQL_ROOT_PASSWORD: "root"
        ports:
            - 3306:3306
        volumes:
            - .dbdata:/var/lib/mysql
        networks:
            - app

networks:
    app:
        driver: bridge

volumes:
    node_modules:
    vendor:
    .env:
