services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile

        environment:
            DB_HOST: mysql
            DB_DATABASE: twitter
            DB_USERNAME: root
            DB_PASSWORD: root
            MAIL_MAILER: smtp
            MAIL_HOST: docker.from.mac.localhost
            MAIL_PORT: 1025
        ports:
            - 8000:8000
            - 1025:1025

        volumes:
            - ./backend:/app/backend

        depends_on:
            - mysql
            - redis
            - elasticsearch

        networks:
            - app

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        tty: true
        ports:
            - 3000:3000
        volumes:
            - ./frontend:/app/frontend
        depends_on:
            - backend
        networks:
            - app

    mysql:
        image: mysql
        environment:
            MYSQL_DATABASE: "twitter"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "root"
            MYSQL_ROOT_PASSWORD: "root"
        volumes:
            - .dbdata:/var/lib/mysql
        networks:
            - app

    redis:
        image: redis
        ports:
            - 6379:6379
        networks:
            - app

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
        volumes:
            - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        environment:
            - "discovery.type=single-node"
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - app

networks:
    app:
        driver: bridge
