services:
    nginx:
        container_name: nginx
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - ./frontend/public:/var/www/html/twitter
            - ./backend/storage/app/public:/var/www/sata/twitter
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - /etc/letsencrypt/:/etc/letsencrypt/
        depends_on:
            - frontend
        networks:
            - app

    backend:
        container_name: backend

        build:
            context: ./backend
            dockerfile: Dockerfile

        environment:
            DB_HOST: mysql
            DB_DATABASE: twitter
            DB_USERNAME: root
            DB_PASSWORD: root

        ports:
            - 8000:8000
            - 1025:1025

        volumes:
            - ./backend:/app/backend
            - vendor:/app/backend/vendor

        depends_on:
            - mysql
            - redis
            - elasticsearch
            - kafka
            - kibana

        networks:
            - app

    frontend:
        container_name: frontend
        build:
            context: .
            dockerfile: frontend/Dockerfile
        tty: true
        ports:
            - 3000:3000
        volumes:
            - ./frontend:/app/frontend
            - ./backend/.env:/app/frontend/.env
            - node_modules:/app/frontend/node_modules
        depends_on:
            - backend
        networks:
            - app

    mysql:
        container_name: mysql
        image: mysql
        environment:
            MYSQL_DATABASE: "twitter"
            MYSQL_USER: "admin"
            MYSQL_PASSWORD: "root"
            MYSQL_ROOT_PASSWORD: "root"
        ports:
            - 3306:3306
        volumes:
            - .dbdata:/var/lib/mysql
        networks:
            - app

    redis:
        container_name: redis
        image: redis
        ports:
            - 6379:6379
        networks:
            - app

    kafka:
        container_name: kafka
        image: wurstmeister/kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - app
        depends_on:
            - zookeeper

    elasticsearch:
        container_name: elasticsearch
        image: elasticsearch:8.10.1
        volumes:
            - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        environment:
            - "discovery.type=single-node"
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - app

    zookeeper:
        container_name: zookeeper
        image: arm64v8/zookeeper
        ports:
            - "2181:2181"
        networks:
            - app

    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:8.10.1
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch:9200
        ports:
            - "5601:5601"
        # volumes:
        #     - ./kibana.yml:/usr/share/kibana/config/kibana.yml
        networks:
            - app
        depends_on:
            - elasticsearch

    prometheus:
        container_name: prometheus
        image: prom/prometheus
        ports:
            - 9090:9090
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        networks:
            - app

    grafana:
        container_name: grafana
        image: grafana/grafana
        ports:
            - 3100:3000
        volumes:
            - grafana_data:/var/lib/grafana
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
        networks:
            - app

networks:
    app:
        driver: bridge

volumes:
    node_modules:
    vendor:
    grafana_data:
