services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile

        environment:
            DB_HOST: mysql
            DB_DATABASE: twitter
            DB_USERNAME: root
            DB_PASSWORD: root
            MAIL_MAILER: smtp
            MAIL_HOST: docker.from.mac.localhost
            MAIL_PORT: 1025
        ports:
            - 8000:8000
            - 1025:1025

        volumes:
            - ./backend:/app/backend
            - vendor:/app/backend/vendor

        depends_on:
            - mysql
            - redis
            - elasticsearch
            - kafka

        networks:
            - app

    frontend:
        build:
            context: .
            dockerfile: frontend/Dockerfile
        tty: true
        ports:
            - 3000:3000
        volumes:
            - ./frontend:/app/frontend
            - ./backend/.env:/app/frontend/.env
            - node_modules:/app/frontend/node_modules
        depends_on:
            - backend
        networks:
            - app

    mysql:
        image: mysql
        environment:
            MYSQL_DATABASE: "twitter"
            MYSQL_USER: "admin"
            MYSQL_PASSWORD: "root"
            MYSQL_ROOT_PASSWORD: "root"
        ports:
            - 3306:3306
        volumes:
            - .dbdata:/var/lib/mysql
        networks:
            - app

    redis:
        image: redis
        ports:
            - 6379:6379
        networks:
            - app

    elasticsearch:
        image: elasticsearch:8.10.1
        volumes:
            - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        environment:
            - "discovery.type=single-node"
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - app

    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
        networks:
            - app

    kafka:
        image: wurstmeister/kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - app
        depends_on:
            - zookeeper

networks:
    app:
        driver: bridge

volumes:
    node_modules:
    vendor:
    .dbdata:
    .env:
