global:
    scrape_interval: 15s

scrape_configs:
    - job_name: "redis_exporter"
      static_configs:
          - targets: ["redis_exporter:9121"]
    - job_name: "twitter"
      static_configs:
          - targets: ["host.docker.internal:8000"]
